
export enum AuthLayer {
  LOGIN = 1,
  PASSPHRASE = 2,
  SESSION_KEY = 3,
  MANUAL_GATE = 4,
  BEHAVIOR_ANALYTICS = 5,
  GEO_FENCING = 6,
  BIOMETRIC = 7,
  DEVICE_FINGERPRINT = 8,
  CONTEXTUAL_RISK = 9,
  AI_BEHAVIORAL = 10,
  SANDBOX_INIT = 11,
  QUANTUM_GATE = 12,
  META_POLICY = 24, 
  AUTHORIZED = 25
}

export enum AIRole {
  OMNI_META_BRAIN_HYPER = 'OMNI_META_BRAIN_HYPER',
  SWARM_AGGREGATOR = 'SWARM_AGGREGATOR',
  ADVERSARIAL_HUNTER_HYPER = 'ADVERSARIAL_HUNTER_HYPER',
  QUANTUM_VERIFIER_ULTRA = 'QUANTUM_VERIFIER_ULTRA',
  SELF_EVOLVE_PATCHER = 'SELF_EVOLVE_PATCHER',
  INTENT_LOCK_REFINER_HYPER = 'INTENT_LOCK_REFINER_HYPER',
  ABSOLUTE_EMITTER = 'ABSOLUTE_EMITTER',
  NEURAL_ARCHITECT = 'NEURAL_ARCHITECT',
  VISUAL_FORGE = 'VISUAL_FORGE',
  SONIC_ENGINEER = 'SONIC_ENGINEER',
  LOGIC_SABOTEUR = 'LOGIC_SABOTEUR',
  META_BRAIN_CONTROLLER = 'META_BRAIN_CONTROLLER',
  SWARM_GENERATOR = 'SWARM_GENERATOR',
  DEBATE_ENGINE_A = 'DEBATE_ENGINE_A',
  DEBATE_ENGINE_B = 'DEBATE_ENGINE_B',
  ERROR_INTELLIGENCE_AUDIT = 'ERROR_INTELLIGENCE_AUDIT',
  FORECAST_ANALYST = 'FORECAST_ANALYST',
  SECURITY_OBSERVER = 'SECURITY_OBSERVER',
  DATA_CURATOR = 'DATA_CURATOR',
  UI_ORCHESTRATOR = 'UI_ORCHESTRATOR',
  MEDIA_RENDERER = 'MEDIA_RENDERER',
  WORKFLOW_MANAGER = 'WORKFLOW_MANAGER',
  PLUGIN_CONTROLLER = 'PLUGIN_CONTROLLER',
  AUTO_UPDATER = 'AUTO_UPDATER',
  SYNCHRONIZER = 'SYNCHRONIZER',
  MONITOR_AGENT = 'MONITOR_AGENT',
  SELF_LEARNING_AGENT = 'SELF_LEARNING_AGENT',
  HOLOGRAPHIC_ENGINEER = 'HOLOGRAPHIC_ENGINEER',
  ARVR_SIMULATOR = 'ARVR_SIMULATOR',
  CROSS_DIMENSIONAL_ANALYST = 'CROSS_DIMENSIONAL_ANALYST',
  QUANTUM_SIMULATOR = 'QUANTUM_SIMULATOR',
  ULTRA_PARALLEL_CONTROLLER = 'ULTRA_PARALLEL_CONTROLLER',
  META_LOGIC_ENGINE = 'META_LOGIC_ENGINE',
  AI_CHAIN_COORDINATOR = 'AI_CHAIN_COORDINATOR',
  INFINITE_LOOP_MONITOR = 'INFINITE_LOOP_MONITOR',
  GODMODE_MANAGER = 'GODMODE_MANAGER',
  META_COGNITION_ENGINE = 'META_COGNITION_ENGINE',
  ULTRA_FORECAST_ANALYST = 'ULTRA_FORECAST_ANALYST',
  HYPER_DIMENSIONAL_ANALYST = 'HYPER_DIMENSIONAL_ANALYST',
  QUANTUM_FORECAST_ENGINE = 'QUANTUM_FORECAST_ENGINE'
}

export enum Modality {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  FILE = 'FILE',
  CODE = 'CODE',
  THREE_D = '3D',
  AR = 'AR',
  VR = 'VR',
  HOLO = 'HOLO',
  HOLO_META = 'HOLO_META',
  HYPER = 'HYPER'
}

export enum PipelineStatus {
  IDLE = 'IDLE',
  META_ANALYSIS = 'META_ANALYSIS',
  SWARM_AGGREGATION = 'SWARM_AGGREGATION',
  ADVERSARIAL_DEBATE = 'ADVERSARIAL_DEBATE',
  QUANTUM_VERIFYING = 'QUANTUM_VERIFYING',
  HEALING = 'HEALING',
  EVOLVING = 'EVOLVING',
  REFINING = 'REFINING',
  EMITTING = 'EMITTING',
  COMPLETED = 'COMPLETED',
  HALTED = 'HALTED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  CONTROLLING = 'CONTROLLING',
  SWARMING = 'SWARMING',
  DEBATING = 'DEBATING',
  AUDITING = 'AUDITING',
  SIMULATING = 'SIMULATING',
  HYPER_DIMENSIONAL = 'HYPER_DIMENSIONAL'
}

export interface AIMessage {
  role: AIRole;
  content: string;
  status: 'success' | 'failure' | 'warning' | 'critical';
  timestamp: string;
}

export interface Task {
  id: string;
  modality: Modality;
  prompt: string;
  status: 'queued' | 'active' | 'completed' | 'failed' | 'paused' | 'escalated' | 'rejected';
  priority: number;
  retryCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface FinalArtifact {
  id: string;
  modality: Modality;
  originalInput: string;
  finalOutput: string;
  sourceChain: AIRole[];
  verificationScore: number; 
  recheckPasses: number;
  logs: string[];
  specs: string;
  createdAt: string;
  safeUsageScope: string;
  limitations: string[];
  emissionSpecs: string;
  rejectedAlternatives: string[];
  humanActionRequired: string | null;
  swarmConsensus: number;
  version: string;
  hash: string;
  resourceUsage: number;
  agentCount: number;
}
